# Details at https://docs.readthedocs.io/en/stable/config-file/v2.html

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

mkdocs:
  configuration: mkdocs.yaml
  fail_on_warning: false

# Optionally declare the Python requirements required to build your docs
python:
  install:
  - requirements: requirements.txt
  - method: pip
    path: .
    extra_requirements:
      - mkdocs-click
      - mkdocs-material
