
debug: false
force: false
profile: "sample"
verbose: false

profiles:
  sample:
    url: "https://synology.photos.sample.server.example.com"
    account: "sample_account"
    password: "sample_password"
